version: "3.5"
services:

  # BCHN full node for gs++ to connect to
  bitcoind1: 
    image: "bchn"
    build:
      context: "."
      dockerfile: "Dockerfile.bchn"
    command: "bitcoind"
    healthcheck:
      test: ["CMD", "/entrypoint.sh", "bitcoin-cli", "getblockchaininfo"]
    expose:
      - "18333" # regnet
      #- "28332" # zmq publish tx/block
    ports:
      - "18443:18443"
      - "28332:28332" # zmq publish tx/block
    volumes:
      - ./bitcoin.conf:/data/bitcoin.conf

  # gs++ connected to bitcoind1
  graphsearch:
    image: "graphsearch"
    build:
      dockerfile: "./Dockerfile.regtest"
      context: ".."
    depends_on:
      bitcoind1:
        condition: service_healthy 
    volumes:
      - ./:/data
    entrypoint: [ "/data/gs++-entrypoint.sh" ]
    ports:
      - "50051:50051"  # gRPC graphsearch service
      - "29069:29069"  # zmq publish

  # Second BCHN for doing double spends
  bitcoind2: 
    image: "bchn"
    build:
      context: "."
      dockerfile: "Dockerfile.bchn"
    command: "bitcoind"
    healthcheck:
      test: ["CMD", "/entrypoint.sh", "bitcoin-cli", "getblockchaininfo"]  # TODO: need to wait for wallet to finish loading.
    expose:
      - "18333" # regnet
      #- "28332" # zmq publish tx/block
    ports:
      - "18444:18443"
    depends_on: 
      - bitcoind1
    volumes:
      - ./bitcoin.conf:/data/bitcoin.conf
